#!/bin/sh 

# Configure Raspberry Pi settings
sudo raspi-config nonint do_i2c 0
sudo raspi-config nonint do_rgpio 0
sudo raspi-config nonint do_spi 0
sudo systemctl enable pigpiod

# Set up virtual environment and run setup script
pathLocale=$(readlink -f .)
chmod +x scriptStarter
python -m venv .venv
source .venv/bin/activate
.venv/bin/python3 setup.py

# Create script starter
printf "#!/bin/sh
sleep 3
cd %s
.venv/bin/python3 src/home.py
exit 0" "$pathLocale" > scriptStarter

# Create systemd service
printf "[Unit]
Description=Magnetism Service
After=multi-user.target
Requires=network.target

[Service]
Type=idle
ExecStart=/usr/bin/sudo %s/scriptStarter
Restart=always
RestartSec=10

[Install]
WantedBy=multi-user.target" "$pathLocale" > /etc/systemd/system/myService.service

chmod 644 /etc/systemd/system/myService.service
systemctl daemon-reload
systemctl enable myService.service

# Ask user if they want to reboot
read -p "Reboot needed, do you want to restart now? [y,n]" doit
case $doit in  
  y|Y) reboot;;  
  *) printf "\nReboot postponed\n" ;;
esac
